package com.erp.aula;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ButtonGroup;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JRadioButton;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.SpinnerDateModel;
import javax.swing.WindowConstants;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JPasswordField;



public class CadastroPessoa extends javax.swing.JFrame implements ActionListener {

    // Configurações do banco de dados
    private static final String DB_URL = "jdbc:postgresql://localhost:5432/cadastropessoa";
    private static final String DB_USER = "postgres";
    private static final String DB_PASSWORD = "1234";
    
    public CadastroPessoa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        buttonGroup1 = new ButtonGroup();
        jTextField4 = new JTextField();
        jLabel1 = new JLabel();
        jLabel2 = new JLabel();
        jLabel3 = new JLabel();
        jLabel4 = new JLabel();
        jTextField1 = new JTextField();
        jTextField2 = new JTextField();
        jTextField3 = new JTextField();
        jLabel5 = new JLabel();
        Feminino = new JRadioButton();
        Masculino = new JRadioButton();
        Outro = new JRadioButton();
        jLabel6 = new JLabel();
        jSpinner1 = new JSpinner();
        jLabel7 = new JLabel();
        jLabel8 = new JLabel();
        jLabel9 = new JLabel();
        jTextField5 = new JTextField();
        jTextField6 = new JTextField();
        jTextField7 = new JTextField();
        CancelarButton = new JButton();
        EnviarButton = new JButton();
        jLabel10 = new JLabel();
        senhaPassword = new JPasswordField();

        jTextField4.setText("jTextField4");

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cadastro Pessoa");

        jLabel2.setText("Nome Completo:");

        jLabel3.setText("Email:");

        jLabel4.setText("Telefone:");

        jLabel5.setText("Sexo:");

        buttonGroup1.add(Feminino);
        Feminino.setText("Feminino");
        Feminino.addActionListener(this);

        buttonGroup1.add(Masculino);
        Masculino.setText("Masculino");
        Masculino.addActionListener(this);

        buttonGroup1.add(Outro);
        Outro.setText("Outro");
        Outro.addActionListener(this);

        jLabel6.setText("Data de Nascimento:");

        jSpinner1.setModel(new SpinnerDateModel());

        jLabel7.setText("Cidade:");

        jLabel8.setText("Estado:");

        jLabel9.setText("Endereço:");

        CancelarButton.setText("Cancelar");
        CancelarButton.addActionListener(this);

        EnviarButton.setText("Enviar");
        EnviarButton.addActionListener(this);

        jLabel10.setText("Defina a senha:");

        senhaPassword.setText("jPasswordField1");
        senhaPassword.addActionListener(this);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinner1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Feminino, GroupLayout.PREFERRED_SIZE, 81, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Masculino, GroupLayout.PREFERRED_SIZE, 98, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Outro, GroupLayout.PREFERRED_SIZE, 98, GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel5, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(0, 118, Short.MAX_VALUE))
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CancelarButton)
                                        .addGap(55, 55, 55)
                                        .addComponent(EnviarButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(120, 120, 120))))
                            .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4, GroupLayout.PREFERRED_SIZE, 91, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(senhaPassword)
                                    .addComponent(jTextField2, GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField1, GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField3, GroupLayout.Alignment.TRAILING)))
                            .addGroup(GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel7))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField5)
                                    .addComponent(jTextField6)
                                    .addComponent(jTextField7))))
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(senhaPassword, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(Feminino)
                    .addComponent(Masculino)
                    .addComponent(Outro))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSpinner1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField6, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField7, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelarButton)
                    .addComponent(EnviarButton))
                .addGap(17, 17, 17))
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(ActionEvent evt) {
        if (evt.getSource() == Feminino) {
            CadastroPessoa.this.FemininoActionPerformed(evt);
        }
        else if (evt.getSource() == Masculino) {
            CadastroPessoa.this.MasculinoActionPerformed(evt);
        }
        else if (evt.getSource() == Outro) {
            CadastroPessoa.this.OutroActionPerformed(evt);
        }
        else if (evt.getSource() == CancelarButton) {
            CadastroPessoa.this.CancelarButtonActionPerformed(evt);
        }
        else if (evt.getSource() == EnviarButton) {
            CadastroPessoa.this.EnviarButtonActionPerformed(evt);
        }
        else if (evt.getSource() == senhaPassword) {
            CadastroPessoa.this.senhaPasswordActionPerformed(evt);
        }
    }//GEN-END:initComponents

    private void enviarCadastro() {
        String nomeCompleto = jTextField1.getText();
        String email = jTextField2.getText();
        String telefone = jTextField3.getText();
        String sexo = "";

        if (Feminino.isSelected()) {
            sexo = "Feminino";
        } else if (Masculino.isSelected()) {
            sexo = "Masculino";
        } else if (Outro.isSelected()) {
            sexo = "Outro";
        }

        java.util.Date dataNascimento = (java.util.Date) jSpinner1.getValue();
        java.sql.Date sqlDate = new java.sql.Date(dataNascimento.getTime());
        String cidade = jTextField5.getText().trim();
        String estado = jTextField6.getText().trim();
        String endereco = jTextField7.getText().trim();
         String senha = new String(senhaPassword.getPassword()); // Coleta a senha
        
        // Validações
    if (nomeCompleto.isEmpty() || email.isEmpty() || telefone.isEmpty() ||
        sexo.isEmpty() || cidade.isEmpty() || estado.isEmpty() || endereco.isEmpty() || senha.isEmpty()) {
        System.err.println("Por favor, preencha todos os campos obrigatórios.");
        return; // Retorna sem cadastrar
    }

        try (Connection conn = DriverManager.getConnection(DB_URL, DB_USER, DB_PASSWORD)) {
            String sql = "INSERT INTO usuarios (nome_completo, email, telefone, sexo, data_nascimento, cidade, estado, endereco, senha) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, nomeCompleto);
            pstmt.setString(2, email);
            pstmt.setString(3, telefone);
            pstmt.setString(4, sexo);
            pstmt.setDate(5, sqlDate);
            pstmt.setString(6, cidade);
            pstmt.setString(7, estado);
            pstmt.setString(8, endereco);
            pstmt.setString(9, senha);
            pstmt.executeUpdate();
            System.out.println("Cadastro realizado com sucesso!");
            
             Login loginScreen = new Login();
        loginScreen.setVisible(true);
        this.dispose(); // Fecha a tela CadastroPessoa
    } catch (SQLException e) {
        System.err.println("Erro ao realizar o cadastro: " + e.getMessage());
        }
    }

    private void OutroActionPerformed(ActionEvent evt) {//GEN-FIRST:event_OutroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OutroActionPerformed

    private void CancelarButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_CancelarButtonActionPerformed
    Login loginScreen = new Login(); // Puxar tela LOGIN
    loginScreen.setVisible(true); // Exibir tela LOGIN
    this.dispose(); // fechar ATUAL
    }//GEN-LAST:event_CancelarButtonActionPerformed

    private void MasculinoActionPerformed(ActionEvent evt) {//GEN-FIRST:event_MasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MasculinoActionPerformed

    private void FemininoActionPerformed(ActionEvent evt) {//GEN-FIRST:event_FemininoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FemininoActionPerformed

    private void EnviarButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_EnviarButtonActionPerformed
    enviarCadastro();
    }//GEN-LAST:event_EnviarButtonActionPerformed

    private void senhaPasswordActionPerformed(ActionEvent evt) {//GEN-FIRST:event_senhaPasswordActionPerformed
 
    }//GEN-LAST:event_senhaPasswordActionPerformed
    /**
      * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroPessoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton CancelarButton;
    private JButton EnviarButton;
    private JRadioButton Feminino;
    private JRadioButton Masculino;
    private JRadioButton Outro;
    private ButtonGroup buttonGroup1;
    private JLabel jLabel1;
    private JLabel jLabel10;
    private JLabel jLabel2;
    private JLabel jLabel3;
    private JLabel jLabel4;
    private JLabel jLabel5;
    private JLabel jLabel6;
    private JLabel jLabel7;
    private JLabel jLabel8;
    private JLabel jLabel9;
    private JSpinner jSpinner1;
    private JTextField jTextField1;
    private JTextField jTextField2;
    private JTextField jTextField3;
    private JTextField jTextField4;
    private JTextField jTextField5;
    private JTextField jTextField6;
    private JTextField jTextField7;
    private JPasswordField senhaPassword;
    // End of variables declaration//GEN-END:variables
}
