/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.erp.aula;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.LayoutStyle;
import javax.swing.WindowConstants;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;

/**
 *
 * @author mary2
 */
public class Login extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jColorChooser1 = new JColorChooser();
        jLabel1 = new JLabel();
        nomeCompletoField = new JTextField();
        confirmarButton = new JButton();
        novocadastroButton = new JButton();
        senhaPassword = new JPasswordField();
        jPanel2 = new JPanel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Login");
        jLabel1.setMaximumSize(new Dimension(50, 30));
        jLabel1.setMinimumSize(new Dimension(50, 30));

        nomeCompletoField.setText("Nome de Usuário");
        nomeCompletoField.addActionListener(this);

        confirmarButton.setText("Confirmar");
        confirmarButton.addActionListener(this);

        novocadastroButton.setText("Novo Cadastro");
        novocadastroButton.addActionListener(this);

        senhaPassword.setText("**********");

        jPanel2.setForeground(new Color(255, 51, 153));

        GroupLayout jPanel2Layout = new GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                    .addComponent(nomeCompletoField, GroupLayout.PREFERRED_SIZE, 131, GroupLayout.PREFERRED_SIZE)
                                    .addComponent(senhaPassword, GroupLayout.PREFERRED_SIZE, 131, GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(confirmarButton)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                        .addComponent(novocadastroButton)))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 57, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(nomeCompletoField, GroupLayout.PREFERRED_SIZE, 46, GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(senhaPassword, GroupLayout.PREFERRED_SIZE, 42, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(novocadastroButton)
                    .addComponent(confirmarButton))
                .addGap(52, 52, 52))
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(ActionEvent evt) {
        if (evt.getSource() == nomeCompletoField) {
            Login.this.nomeCompletoFieldActionPerformed(evt);
        }
        else if (evt.getSource() == confirmarButton) {
            Login.this.confirmarButtonActionPerformed(evt);
        }
        else if (evt.getSource() == novocadastroButton) {
            Login.this.novocadastroButtonActionPerformed(evt);
        }
    }//GEN-END:initComponents

    private void nomeCompletoFieldActionPerformed(ActionEvent evt) {//GEN-FIRST:event_nomeCompletoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeCompletoFieldActionPerformed

    private void novocadastroButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_novocadastroButtonActionPerformed
    CadastroPessoa cadastroPessoa = new CadastroPessoa();
    cadastroPessoa.setVisible(true);

    this.dispose(); // Fecha a tela de Login
    }//GEN-LAST:event_novocadastroButtonActionPerformed

    private void confirmarButtonActionPerformed(ActionEvent evt) {//GEN-FIRST:event_confirmarButtonActionPerformed
        String nomeCompleto = nomeCompletoField.getText();
        String senha = new String(senhaPassword.getPassword());

        // método de validação          
        validarLogin(nomeCompleto, senha);
    }//GEN-LAST:event_confirmarButtonActionPerformed

        private void validarLogin(String nomeCompleto, String senha) {
        String sql = "SELECT * FROM usuarios WHERE nome_completo = ? AND senha = ?";
        
        try (Connection conn = ConexaoBanco.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql)) {
            
            stmt.setString(1, nomeCompleto);
            stmt.setString(2, senha);
            
            try (ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    JOptionPane.showMessageDialog(this, "Login bem-sucedido!");
                    // Redireciona para a tela de cadastro de produtos
                CadastroProduto cadastroProduto = new CadastroProduto();
                cadastroProduto.setVisible(true);
                this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Nome ou senha incorretos!");
                }
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Erro ao conectar ao banco de dados: " + e.getMessage());
        }
    }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton confirmarButton;
    private JColorChooser jColorChooser1;
    private JLabel jLabel1;
    private JPanel jPanel2;
    private JTextField nomeCompletoField;
    private JButton novocadastroButton;
    private JPasswordField senhaPassword;
    // End of variables declaration//GEN-END:variables
}
